// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/luist1228/go-htmx-examples/templates/components"

func Main(title string, content templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/views/layouts/main.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><script src=\"https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js\"></script><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\"></script><link rel=\"stylesheet\" href=\"/assets/css/tailwind.css\"><link rel=\"stylesheet\" href=\"https://cdn.xeiaso.net/static/pkg/iosevka/family.css\"><script>\n\t\t\t\t// Change localStorage setItem function so that it emits change event within the same page\n\t\t\t\tconst origSetItem = window.localStorage.setItem;\n\n\t\t\t\twindow.localStorage.setItem = function setItem(key, value) {\n\t\t\t\t\t// Retrieve old value before we store the new one\n\t\t\t\t\tlet oldValue = window.localStorage.getItem(key);\n\t\t\t\t\t// Store in LocalStorage\n\t\t\t\t\tconst result = origSetItem.apply(this, arguments);\n\n\t\t\t\t\t// Manually fire a \"storage\" event so this window is alerted. On its own, \n\t\t\t\t\t// localStorage.setItem() only fires a \"storage\" event for other tabs.\n\t\t\t\t\tconst e = new StorageEvent('storage', {\n\t\t\t\t\t\tstorageArea: window.localStorage,\n\t\t\t\t\t\tkey,\n\t\t\t\t\t\toldValue,\n\t\t\t\t\t\tnewValue: value,\n\t\t\t\t\t\turl: window.location.href,\n\t\t\t\t\t});\n\t\t\t\t\twindow.dispatchEvent(e);\n\n\t\t\t\t\treturn result;\n\t\t\t\t}\n\t\t\t</script></head><body><main class=\" flex flex-col items-center h-full min-h-screen bg-base-300\"><div class=\"navbar bg-base-200\"><div class=\"navbar-start\"><a href=\"/\" class=\"btn bg-base-100 text-xl\"><span class=\"text-primary\">GO + &lt;<b>/</b>&gt; htm<b>x</b></span></a></div><div class=\"navbar-center\"></div><div class=\"navbar-end\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ThemeDropdown().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><section class=\" w-full px-4 md:w-3/4 lg:w-1/2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if content != nil {
			templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
