// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/luist1228/go-htmx-examples/templates/components"
import "github.com/luist1228/go-htmx-examples/db"

func customSortForm() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_customSortForm_3f75`,
		Function: `function __templ_customSortForm_3f75(){htmx.on("end", ()=>{
		const form = document.getElementById("sort-form")
		if(form){
			form.replaceChildren("")
		}
		const todos = document.querySelectorAll("input[name='sort-id']")
		if(todos.length > 0 ){
			todos.forEach((input)=>{
				const newInput= document.createElement("input")
				newInput.setAttribute("type","hidden")
				newInput.setAttribute("name","id")
				newInput.setAttribute("value", input.value)
				form.appendChild(newInput)
				htmx.process(newInput)
			})
			htmx.trigger("#sort-form","custom-end")

			htmx.on("htmx:afterSwap", function(){
				form.replaceChildren("")
			})
		}
	})


}`,
		Call:       templ.SafeScript(`__templ_customSortForm_3f75`),
		CallInline: templ.SafeScriptInline(`__templ_customSortForm_3f75`),
	}
}

func TodosView(todos db.Todos) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.SearchTodo().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form method=\"POST\" action=\"/todos/sort\" hx-post=\"/todos/sort\" hx-trigger=\"custom-end\" hx-target=\"#todos\" hx-swap=\"outerHTML\" id=\"sort-form\" enctype=\"multipart/form-data\"></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Todos(todos).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = customSortForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AddTodo().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
