// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/luist1228/go-htmx-examples/db"

func loadSorting() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_loadSorting_2bb1`,
		Function: `function __templ_loadSorting_2bb1(){var sortables = document.querySelectorAll(".sortable");
	for (var i = 0; i < sortables.length; i++) {
		var sortable = sortables[i];
		var sortableInstance = new Sortable(sortable, {
				draggable: '.draggable',
				handle:'.handle',
				animation: 150,
				chosenClass: 'dragClass',
				// Make the ` + "`" + `.htmx-indicator` + "`" + ` unsortable
				filter: ".htmx-indicator",
				onMove: function (evt) {
					return evt.related.className.indexOf('htmx-indicator') === -1;
				},

				// Disable sorting on the ` + "`" + `end` + "`" + ` event
				onEnd: function (evt) {
					this.option("disabled", true);
				}
		});

		// Re-enable sorting on the ` + "`" + `htmx:afterSwap` + "`" + ` event
		sortable.addEventListener("htmx:afterSwap", function() {
			sortableInstance.option("disabled", false);
		});
	}


	
}`,
		Call:       templ.SafeScript(`__templ_loadSorting_2bb1`),
		CallInline: templ.SafeScriptInline(`__templ_loadSorting_2bb1`),
	}
}

func Todos(todos db.Todos) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"space-y-2 my-2 sortable\" id=\"todos\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, todo := range todos {
			templ_7745c5c3_Err = Todo(*todo).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = loadSorting().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
